# Generated by Django 4.1 on 2023-08-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_contactusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='first_name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='last_name',
            field=models.CharField(max_length=160),
        ),
    ]
