# Generated by Django 4.1 on 2023-08-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery', '0014_alter_gallerymodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='gallery_img',
            field=models.ImageField(default='default.jpg', upload_to='gallery'),
        ),
    ]
